# Generated by Django 2.2.13 on 2020-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='User', max_length=20)),
                ('UrlName', models.CharField(max_length=100)),
                ('Output', models.CharField(max_length=20)),
            ],
        ),
    ]
